version: '3.6'

services:
  mysql:
    image: mariadb:${MARIADB_VERSION:-latest} # port 3306 exposed
    container_name: ${STACK_PREFIX:-HWD}mysql
    volumes:
    - ./mysql:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
    - MYSQL_DATABASE=${MYSQL_DATABASE:-wordpress}
    - MYSQL_USER=${MYSQL_USER:-root}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
    restart: always

  wordpress: # create service wordpress:9000 in the :network
    image: wordpress:${WORDPRESS_VERSION:-php7.3-fpm} # port 9000 exposed
    container_name: ${STACK_PREFIX:-HWD}wordpress
    volumes:
      - ./wordpress:/var/www/html

    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST:-mysql}

      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME:-wordpress}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER:-root}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD:-password}
      - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX:-wp_}

    depends_on:
      - mysql
    restart: always

  nginx:
    image: nginx:${NGINX_VERSION:-latest}
    container_name: ${STACK_PREFIX:-HWD}nginx
    ports:
      - ${NGINX_HTTP_PORT:-80}:80
      - ${NGINX_HTTPS_PORT:-443}:443
    volumes:
      - ${NGINX_CONF_DIR:-./nginx}:/etc/nginx/conf.d # nginx will delegate PHP-request to wordpress:9000 in $CODE/nginx/default.conf at `fastcgi_pass wordpress:9000;`

      - ${NGINX_LOG_DIR:-./logs/nginx}:/var/log/nginx

      - ${SSL_CERTS_DIR:-./certs}:/etc/letsencrypt
      - ${SSL_CERTS_DATA_DIR:-./certs-data}:/data/letsencrypt

      # binding created bw. :nginx vs :wordpress
      # i.e.
      # :nginx service/container and :wordpress service/container mapped to the **SAME /var/www/html** folder
      - ${WORDPRESS_DATA_DIR:-./wordpress}:/var/www/html

    depends_on:
      - wordpress
    restart: always

networks:
  default:
    name: ${NETWORK_NAME:-hostingwithdocker}
